export const positive = "NEW PATCH RELEASED";
export const negative = [
  "Nothing new",
  "PepeHands",
  "NotLikeThis",
  "john_travolta_looking_around.gif",
  "modCheck",
  "No patch yet",
  "nope!",
  "no.",
  "nej",
  "nein",
  "net",
  "non",
  "Maybe soon but not yet",
  "From the Ghastly Eyrie I can see to the ends of the world, and from this vantage point I declare with utter certainty that the patch hasn't dropped yet!",
  "[ALL] SORROWFUL BEEPS",
  "'It's not time yet' - Night Stalker, 2022",
  "Patch leak: Patch Release Time nerfed by 25%",
  "༼ つ ◕_◕ ༽つ Give patch",
  "Wykhym: patch nerfed",
  "February 23, 2023?",
  "Update 31 is here! Please type “update” to update Dota Patch Checker to 0.31!",
  "Copium masks will drop down from above your seat",
  "Please look under your seat for a free bottle of HOPIUM",
  "Non-believers still correct… FOR NOW",
  "The patch is out and I am 12k mmr",
  "Don't count on it",
  "My reply is no",
  "My sources say no",
  "Outlook not so good",
  "Very doubtful",
  "What’s the similarity between your hunky ass on valentines day and Dota 2 Game Client today? Neither are out of dates ;)",
  "Patch remains unreleased as Purge is still not mounted atop his Caffeinated Gamer Chair, and as such remains unable to guide us through the vortex of patch notes for the coming millennia",
  "Numerous eye witnesses reporting that SirActionSlacks has broken free",
  "SirActionSlacks has been spotted outside Valve HQ - Icefrog in protective lockdown",
  "SirActionSlacks is still at large.",
  "Annoyed Windranger noises",
  "Our reporter on the ground is saying that SirActionSlacks is holding what appears to be... Oh for the love of GabeN, no...",
  "No new information on the SirActionSlacks situation",
];
